# Generated by Django 3.1 on 2020-08-19 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=10)),
                ('itier_name', models.CharField(max_length=100)),
                ('itier_lat', models.CharField(max_length=300)),
                ('itier_long', models.CharField(max_length=300)),
                ('my_num', models.IntegerField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bref_info', models.CharField(max_length=100)),
                ('keyword1', models.CharField(max_length=10)),
                ('keyword2', models.CharField(max_length=10)),
                ('keyword3', models.CharField(max_length=10)),
                ('want_gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('X', '전부')], max_length=1)),
                ('want_num', models.IntegerField()),
                ('want_age', models.IntegerField(blank=True, choices=[(10, '10대'), (20, '20대'), (30, '30대'), (40, '40대'), (50, '50대'), (60, '60대 이상')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toLike', models.IntegerField(default=2)),
                ('fromLike', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mate', to='feeds.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_info', to='feeds.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='feeds.trip')),
            ],
        ),
    ]
